# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import glo
import os
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QDialog, QMainWindow
from PyQt5.QtCore import Qt

import resource_Dialog

# class ChildDialogUi(QDialog):
#     def __init__(self):
#         super().__init__()
#         self.setWindowFlags(Qt.WindowCloseButtonHint)

class Ui_Dialog(object):
    def setupUi(self, Dialog,str):
        Dialog.setWindowFlags(Qt.WindowCloseButtonHint)
        Dialog.setObjectName("Dialog")
        Dialog.resize(782, 949)
        Dialog.setMinimumSize(QtCore.QSize(782, 949))
        Dialog.setMaximumSize(QtCore.QSize(782, 949))
        Dialog.setStyleSheet("background-color: rgb(170, 255, 255);")

        self.root='./screenshots/'

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./logo/对联1.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)


        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(130, 120, 525, 815))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")

        self.input=glo.get_value('INPUT_TEXT')
        self.output=glo.get_value('OUTPUT_TEXT')
        self.dir_list = os.listdir(self.root)
        self.length = len(self.dir_list)
        self.index = self.dir_list.index('{0},{1}.jpg'.format(self.input,self.output))

        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(10, 430, 111, 121))
        self.pushButton.setStyleSheet("border-image: url(:/background/向左1.png);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.on_pushButton_clicked)


        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(660, 430, 111, 121))
        self.pushButton_2.setStyleSheet("border-image: url(:/background/向右1.png);")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.on_pushButton_2_clicked)


        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(130, 40, 521, 71))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 18pt \"华文隶书\";")
        self.label_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        # QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.show_img(str)
    def show_img(self,filestr):
        # img = r'./screenshots/{0},{1}.jpg'.format(self.input, self.output)
        self.screenshot = QPixmap(filestr)
        # self.screenshot.save('./screenshots/1.jpg')
        self.label.setPixmap(self.screenshot)
        # 图片自适应窗口大小
        # self.label.setScaledContents(True)

    def on_pushButton_clicked(self):
        if self.index >0:
            self.index -= 1
        else:
            self.index = self.length-1
        filename = self.dir_list[self.index]
        file=os.path.join(self.root,filename)
        self.show_img(file)


    def on_pushButton_2_clicked(self):
        if self.index < self.length-1:
            self.index += 1
        else:
            self.index = 0
        filename = self.dir_list[self.index]
        file=os.path.join(self.root,filename)
        self.show_img(file)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "AI为您精心定制的对联"))
        self.label_2.setText(_translate("Dialog", "向左或者向右查看历史截图"))
